# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b6316e8e86a1feb12944ab4d853c116e7a916d83502a500bf26f783b2746a60ab0b8c55678556dfec309ba98b639299bf99223843c9c583012be3b9979cee7

test:
  secret_key_base: e9688e2f5460da540cadffb1ccfefff212f250f58422708ab370e04f2eab57ee880ed5456e011ada8e3a88ab332c890a20c700071685af0a1cfe796349a997c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
